apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-demo
  name: deployment-python-demo
spec:
  selector:
    matchLabels:
      app: python-demo
  template:
    metadata:
      labels:
        app: python-demo
    spec:
      containers:
        - image: '192.168.17.1:60080/devops/python-demo'
          name: python-demo
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 5000
